name: Lint and format

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: prettier-check
        run: npx prettier --check .
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: install wasm-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build opaque
        run: pnpm build
      - name: Run typechecks
        run: pnpm typecheck
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain none
      - name: install rustfmt
        run: rustup component add rustfmt
      - name: rustfmt
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain none
      - name: install clippy
        run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
