name: Release

on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: install wasm-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install
      - name: install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          publish: pnpm changeset-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
