name: Tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: install wasm-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install
      - name: Build opaque
        run: pnpm build
      - name: tests
        run: pnpm test
